name: xrVal
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.11
  - xesmf
  - pyproj
  - pysteps
  - xskillscore
  - zarr
  - esmpy
  - setuptools
  - xarray
  - dask
  - numpy
  - scipy
  - matplotlib
  - pandas
  - netcdf4
  - jupyter
  - h5py
  - h5netcdf